from decouple import config

AWS_ACCESS_KEY_ID     = config("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
REGION_NAME           = config("REGION_NAME")

COUNTRY_ADO_ID_TABLE = config("COUNTRY_ADO_ID")
ADO_ATHLETE = config("ADO_ATHLETE")
USER_PROFILE = config("USER_PROFILE")