import os

AWS_ACCESS_KEY_ID     = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
REGION_NAME           = os.getenv("REGION_NAME")

COUNTRY_ADO_ID_TABLE = os.getenv("COUNTRY_ADO_ID")
USER_PROFILE = os.getenv("USER_PROFILE")