apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-account-service-deployment
  labels:
    app: cas 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cas 
  template:
    metadata:
      labels:
        app: cas  
    spec:
      containers:
      - name: cas 
        image: distributed07/create-account-service:latest
        imagePullPolicy: Always
        workingDir: /app
        command: ["/bin/sh","-c"]
        args: ["gunicorn app:app --bind 127.0.0.1:5000 --log-level=debug"]
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: REGION_NAME
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: REGION_NAME
        - name: COUNTRY_ADO_ID
          value: "CountryAdoId"
        - name: USER_PROFILE
          value: "UserProfile"

---
apiVersion: v1
kind: Service
metadata:
  name: create-account-service
spec:
  type: LoadBalancer
  selector:
    app: cas
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: create-account-service
