apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-athlete-test-service-deployment
  labels:
    app: sats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sats
  template:
    metadata:
      labels:
        app: sats
    spec:
      containers:
        - name: sats
          image: distributed07/schedule-athlete-test-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          workingDir: /app
          command: ["/bin/sh", "-c"]
          args: ["gunicorn app:app --bind 0.0.0.0:5000 --log-level=debug"]
          ports:
            - containerPort: 5000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: REGION_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-athlete-test-service
spec:
  type: LoadBalancer
  selector:
    app: sats
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: schedule-athlete-test-service
