apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-deployment
  labels:
    app: as
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as
  template:
    metadata:
      labels:
        app: as
    spec:
      containers:
        - name: as
          image: distributed07/account-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          workingDir: /app
          command: ["/bin/sh", "-c"]
          args: ["gunicorn app:app --bind 0.0.0.0:5000 --workers 4 --log-level=debug"]
          ports:
            - containerPort: 5000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: REGION_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: distributed_bois
spec:
  loadBalancerIP: 20.224.88.180
  type: LoadBalancer
  selector:
    app: as
  ports:
    - port: 2000
      targetPort: 5000
      name: account-service
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: account-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: account-service-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50