apiVersion: apps/v1
kind: Deployment
metadata:
  name: update-athlete-availability-service-deployment
  labels:
    app: uaas 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uaas 
  template:
    metadata:
      labels:
        app: uaas  
    spec:
      containers:
      - name: uaas 
        image: distributed07/update-athlete-availability-service:latest
        imagePullPolicy: Always
        workingDir: /app
        command: ["/bin/sh","-c"]
        args: ["gunicorn app:app --bind 127.0.0.1:5000"]
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: REGION_NAME
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: REGION_NAME
        
        ### add all environment variables you need here; table names dont need to in secret ###
        - name: COUNTRY_ADO_ID
          value: CountryAdoId
---
apiVersion: v1
kind: Service
metadata:
  name: update-athlete-availability-service
spec:
  type: LoadBalancer
  selector:
    app: uaas
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: update-athlete-availability-service



