name: Build Docker Images CI

on:
  push:
    branches: [ main ]
    paths: Backend/Services/create-account-service/**
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push create-account-service
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: distributed07/create-account-service:latest
          platforms: linux/arm64,linux/amd64
          context: ./Backend/Services/create-account-service
